### ISSUE TITLE
Please help me with fix my lang

### ISSUE THREAD

**Issue by weerawat8597** [hrydgard/ppsspp-lang#430]
Please help me with a modified form of the language. The Format It is incorrect Examples such as the correct is  Confirm Overwrite = ต้องการให้เขียนทับข้อมูลเดิมหรือไม่?
but Language displayed on andriod format is not correct my language.
![screenshot_2014-12-29-22-39-39](https://cloud.githubusercontent.com/assets/8061421/5570469/5ba4f148-8fb4-11e4-82d4-738e0a8276ff.png)

**Comment by unknownbrackets** [comment]
Some Thai characters are probably missing from the font atlas, which is used outside of Windows and Qt.

-[Unknown]

**Comment by vnctdj** [comment]
@unknownbrackets Just curious, why do we need a font atlas and how does it work ?

**Comment by unknownbrackets** [comment]
The font atlas is a big image that has all the letters (and also some symbols and other things) on it.  Like this:

```
ABCDEFGHI....
123567890....
!_+{}[]()...
```

It has characters not just from Latin, but from other languages as well.  If it doesn't have a Thai character, then we can't draw that character - we can only draw the characters it has.  But, including ALL Chinese, Japanese, Korean, Thai, etc. characters is A LOT of characters.  Our current approach simply won't work for that, many phones don't support image/textures that large.

Anyway, when drawing text on screen, we use these characters.  In other words, it's basically a font.  The reasons for this are:

1. We render everything in OpenGL.  Ultimately, we *need* everything in an image to draw it to a screen (we're not using OS widgets anywhere.)

2. It avoids us having to deal with font library issues on various platforms.

3. It's easier - we had it from the beginning, and the font rendering APIs on various platforms are more work.

On Windows, we ask the operating system to render to small images (sentences) and then use those images.  This was added at some point.  Windows is the *only* platform that respects the "Font" setting.  Android and others ignore it.

Qt does also draw "sentences."  AFAIK they are always drawn in the system default font, e.g. Arial, and the "Font" setting is always ignored.

On Android, Linux, and maybe other platforms, we could implement freetype2 and maybe do what we do on Windows.  On Linux especially, we might hit various "fontconfig" issues, but Android would definitely benefit form the effort.  It just hasn't been done by anyone yet.

By the way, this is also how games often draw text.  Usually they simply use a texture that has all the characters they expect to ever draw, exactly like we do, and use it exactly the way we do.

-[Unknown]

**Comment by hrydgard** [comment]
Freetype2 alone isn't enough to match what Windows does for us, we would also need Harfbuzz for text layout for some scripts (mostly the ones that we can't possibly render correctly using our atlas like Arabic and various Indian scripts).

On Android we are probably better off using the operating system's font rendering from Java, rendering to bitmaps that we would then pass to OpenGL.

**Comment by unknownbrackets** [comment]
Oh, that's a good point.

-[Unknown]

**Comment by vnctdj** [comment]
Thanks for your explanation @unknownbrackets, as always :)
I didn't know we treated font as images...
