### ISSUE TITLE
Duplicate string(?)

### ISSUE THREAD

**Issue by VIRGINKLM** [hrydgard/ppsspp-lang#463]
Aren't those duplicates?

https://github.com/hrydgard/ppsspp-lang/blob/master/en_US.ini#L536

https://github.com/hrydgard/ppsspp-lang/blob/master/en_US.ini#L540

**Comment by vnctdj** [comment]
No, the 2 strings are existing : 
https://github.com/hrydgard/ppsspp/blob/master/Core/SaveState.cpp#L513
https://github.com/hrydgard/ppsspp/blob/master/Core/SaveState.cpp#L516

**Comment by VIRGINKLM** [comment]
But don't they serve exactly the same purpose?

**Comment by vnctdj** [comment]
Maybe... I unfortunately don't know :/

**Comment by VIRGINKLM** [comment]
@hrydgard any input on that?

**Comment by sum2012** [comment]
As comment in the code,it is trying not to break old lang files

**Comment by vnctdj** [comment]
Yes, I have seen that.
The thing we should know is if these 2 strings are really used for exactly the same purpose.
Or maybe only one is used and the other is ignored ?

**Comment by VIRGINKLM** [comment]
Removing one of them won't break anything. They seem to serve exactly the same purpose. We just mark one of them as obsolete and we remove it, it happened in the past too.
