### ISSUE TITLE
Help me

### ISSUE THREAD

**Issue by Endarko** [hrydgard/ppsspp-lang#513]
I want to add the Java language in ppsspp how?

**Comment by vnctdj** [comment]
What do you mean by "Java language" ?
If you need help about your last pull request, I replied to you there :)

**Comment by Endarko** [comment]
Java language is the language that is in Indonesia, if I may be added
to ppsspp, I will change it to the Java language

**Comment by vnctdj** [comment]
If I am understanding correctly, you want to add a new language which is [Javanese](https://en.wikipedia.org/wiki/Javanese_language) ?
That's what I have found for "Java language"...

**Comment by Endarko** [comment]
ppsspp probably will be unique. because there is no application in Indonesia
and worldwide. which uses the Java language,

**Comment by mgaver** [comment]
I added jv_ID.ini.
Now you can translate it to javanese.
