### ISSUE TITLE
Javanese Lang

### ISSUE THREAD

**Issue by Endarko** [hrydgard/ppsspp-lang#517]
Javanese language do not input into ppsspp first because I have not finished the
translation

**Comment by mgaver** [comment]
If you've finished translation, make a pull request.
Then we will merge it.

**Comment by Endarko** [comment]
ceck issue

**Comment by Endarko** [comment]
ceck pull requests

**Comment by Endarko** [comment]
ceck pull requests

**Comment by mgaver** [comment]
It's merged

**Comment by Endarko** [comment]
ok. thank Mgaver
