### ISSUE TITLE
Need some missing strings

### ISSUE THREAD

**Issue by natuschaos** [hrydgard/ppsspp-lang#595]
The following strings need to be added to en_us.ini in order to be translated to other languages:

"Use UI background" *Found when we hold a finger or mouse on a game to show the start menu and cheats, etc.
"One moment please..." *The popup who aplly the UI image from the game on the menu cited above.
"AVI Dump started."
"AVI Dump stoped." *White text that show us recording screen is starting and stoping if turned on settings.

**Comment by natuschaos** [comment]
Hey @unknownbrackets, sorry to comment on this, I don't want to make a new issue for unplemented strings. But I still found some lines that don't exist the ini.

"Include a screenshot" *When reporting a feedback about a game emulation
"WARNING: Android battery saver mode is on" *You know, very common in Samsung phones

The last is about that one you added, "One moment please..." the title of popup need to be implemented too:
![setting background string](https://cloud.githubusercontent.com/assets/23426146/26775585/e3d9d76e-49ab-11e7-8d76-7cd73e48bba1.png)

**Comment by unknownbrackets** [comment]
Use:

```
[System]
WARNING: Android battery save mode is on = WARNING: Android battery save mode is on
WARNING: Battery save mode is on = WARNING: Battery save mode is on

[Game]
Setting Background = Setting Background

[Reporting]
FeedbackIncludeScreen = Include a screenshot
```

Mostly, you can just search ppsspp's source (https://github.com/hrydgard/ppsspp/search) or use the dump ini feature under developer tools (it seems to save in the wrong folder, though.)

-[Unknown]
