### ISSUE TITLE
Text auto line up, when add "space"  between English & Thai character, without the "\n" signs.

### ISSUE THREAD

**Issue by Saramagrean** [hrydgard/ppsspp-lang#629]
Excuse me, I have a issue. :D

Some categories (like Dialog & Error) when add space (Spacebar) between English and Thai characters without the "/n" signs, Text is auto new line up.

Example: ChangingGPUBackends = เมื่อเปลี่ยนแปลงรูปแบบการสนับสนุนของจีพียู\nกรุณาเริ่ม PPSSPP ใหม่อีกครั้งนึง ต้องการรีสตาร์ทเลยไหม? 
![untitled](https://user-images.githubusercontent.com/26355472/32787050-29236fa4-c988-11e7-8d12-2d9d0ba6b5fa.png)
I want just to show two lines only.

Here, on PPSSPP. It's show three lines. 
![ppsspp v1 4 2-784-g0facf7d52 11_14_2017 9_59_59 pm](https://user-images.githubusercontent.com/26355472/32787030-1dc9c90a-c988-11e7-84e7-4ec66068c6f1.png)

**Comment by unknownbrackets** [comment]
So the issue here is that it's wrapping the second line when it doesn't need to, right?

I think it might be based on the height of the first line.  Does it only happen when you have a \n somewhere?

-[Unknown]

**Comment by Saramagrean** [comment]
Thanks for replied!, and Sorry for my bad english. 😂

From above, I use... ChangingGPUBackends = เมื่อเปลี่ยนแปลงรูปแบบการสนับสนุนของจีพียู\nกรุณาเริ่ม PPSSPP ใหม่อีกครั้งนึง ต้องการรีสตาร์ทเลยไหม?, for need to display only two lines.

Lastwork: v.1.4.2 build 112, text is displayed normal two line.

![92](https://user-images.githubusercontent.com/26355472/32833046-2131af10-ca30-11e7-9e21-243485db8bc8.png)


Firstbreak: v.1.4.2 build 120, text is auto short wrapping to three line.

![91](https://user-images.githubusercontent.com/26355472/32833130-6b496fc0-ca30-11e7-9f36-76ed56b88c45.png)

I tried delete the "\n" sign... ChangingGPUBackends = เมื่อเปลี่ยนแปลงรูปแบบการสนับสนุนของจีพียู กรุณาเริ่ม PPSSPP ใหม่อีกครั้งนึง ต้องการรีสตาร์ทเลยไหม?, It's work displayed two line, but is not make sense for my language. :P 

![93](https://user-images.githubusercontent.com/26355472/32841804-ed2b9e6a-ca4d-11e7-8a4a-bf27e14119c7.png)

When delete the "\n" sign and delete "space" between English and Thai characters... ChangingGPUBackends = เมื่อเปลี่ยนแปลงรูปแบบการสนับสนุนของจีพียู กรุณาเริ่ม PPSSPP ใหม่อีกครั้งนึง ต้องการรีสตาร์ทเลยไหม?, It's displayed normal two line.

![94](https://user-images.githubusercontent.com/26355472/32842014-96318d58-ca4e-11e7-997e-5e9059a6dd47.png)

On Android the "\n" sign is not working, Since v1.4.2 build 177, and only show by one line.

![23634312_593902140941051_636990745_o](https://user-images.githubusercontent.com/26355472/32841325-8f3c9bc0-ca4c-11e7-852c-8cbf025b40b0.png)

Thank you agian!!

**Comment by hrydgard** [comment]
As this is not a translation issue but a text rendering issue, I created an issue in the main project so it doesn't get forgotten as easily: https://github.com/hrydgard/ppsspp/issues/10217

**Comment by Saramagrean** [comment]
OK, Thanks. 😀
