### ISSUE TITLE
PC and Android versions don't match (Farsi/Arabic)

### ISSUE THREAD

**Issue by leopard20** [hrydgard/ppsspp-lang#666]
I know this isn't really PPSSPP's fault, but the Android version translations are messed up. It looks fine on PC:
**PC**:
![image](https://user-images.githubusercontent.com/16115820/40133311-947ffde2-5954-11e8-9c59-b7a4afd94e0c.png)

**Android**:
![screenshot_2018-05-16-22-02-06-614_org ppsspp ppsspp](https://user-images.githubusercontent.com/16115820/40133412-ec5938a8-5954-11e8-9094-49f007c69ae5.png)

I think it's because Android doesn't have a proper RTL implementation.

I was hoping you could provide some tips for fixing it.

**Comment by vnctdj** [comment]
Maybe the difference you see is related to the font used by each system?

**Comment by leopard20** [comment]
Maybe, but the Arabic font kinda looks the same as the Farsi one. So shouldn't they both be bugged?

**Comment by hrydgard** [comment]
On both Windows and Android, we just tell the system to "draw this text on this bitmap please" and hope for the best. It's possible that there's a different way we should do it, or some flag to set or something.. Or Android support for Farsi on that particular version of Android or something might just be broken? Have you tried on other devices?

**Comment by leopard20** [comment]
No, but I'll test it later.
I just found it weird that it worked on Windows but not on Android. I wish I could build the app my own so I could try changing a few things to figure out what the problem is.
Another strange thing is everything looks good in the Graphics submenu, but not in others.

**Comment by hrydgard** [comment]
Could be some nonstandard use of RTL markers in the ini? or failure of PPSSPP to load them correctly from there..

**Comment by leopard20** [comment]
Just added this line:👆
Do you think if I replace the lang file in the apk package directly it'll work?

**Comment by leopard20** [comment]
Actually your word "nonstandard" gave me an idea as to what the problem may be.
Basically Windows supports two types of Farsi keyboards: One is called Farsi (abbreviated as FA) and another Farsi Standard (FAS). I probably have accidentally switched between the two during translation and it may have caused an issue. Don't know which one is the one that worked though!

**Comment by unknownbrackets** [comment]
It seems to mostly have a problem when non rtl glyphs are in a string?  Or an I mistaken?

-[Unknown]

**Comment by leopard20** [comment]
To state it more accurately, it happens when non RTL words are in the middle. If I put them at the end then there's no problem. 
Maybe I was wrong about keyboards!

**Comment by Florin9doi** [comment]
@leopard20 , is this the expected way ? 
![screenshot_1541765431](https://user-images.githubusercontent.com/2995486/48261979-891d7000-e429-11e8-96cc-4602fde7da94.png)

```diff --git a/ar_AE.ini b/ar_AE.ini
index bf0db1b..7586381 100644
--- a/ar_AE.ini
+++ b/ar_AE.ini
@@ -866,7 +866,7 @@ PSP-2000/3000 = PSP-2000/3000
 Record Audio = تسجيل الصوت
 Record Display = سجل الفيديو
 Reset Recording on Save/Load State = Reset recording on Save/Load state
-Restore Default Settings = إلي الإفتراضي PPSSPP's إعادة إعدادات
+Restore Default Settings = <U+200E>إلي الإفتراضي PPSSPP's إعادة إعدادات
 Rewind Snapshot Frequency = ترجيع تردد اللقطة (يأكل الذاكرة)
 Save path in installed.txt = installed.txt مسار الحفظ في
 Save path in My Documents = مسار الحفظ في مستنداتي
```
