### ISSUE TITLE
Update en_us.ini to the latest version.

### ISSUE THREAD

**Issue by AkiraJkr** [hrydgard/ppsspp-lang#675]
There are several missing strings on this one.

**Comment by vnctdj** [comment]
As I said in https://github.com/hrydgard/ppsspp-lang/issues/654, I'm currently working on a tool in order to automate as most actions related to this repository as possible.
Therefore I plan to update _en_US.ini_ relatively soon :)

**Comment by gary-ts** [comment]
vnctdj will release new en_US.ini soon, but this file is OK too.
[en_US.ini.gz](https://github.com/hrydgard/ppsspp-lang/files/2517883/en_US.ini.gz)

PPSSPP is a great emulator, but it is not good to generate translation messages automatically.
* PPSSPP uses "category->T()" for translation messages, but there are many irregular entries.
// UI/GameSettingsScreen.cpp
// static const char *renderingMode[] = { "Non-Buffered Rendering", "Buffered Rendering"};
* Some notes are added manually to en_US.ini.
// Non-Buffered Rendering = Skip buffer effects (non-buffered, faster)
* Some files are not UTF-8 (This is not critical. We can convert it easily).
// ext/xbrz/xbrz.cpp

I can't generate "satisfied" en_US.ini automatically.
I generated unsatisfied en_US.ini.new by my tool "update_en_US.rb",
and I ran "diff -u en_US.ini en_US.ini.new > en_US.ini.diff".
I added new entries manually to en_US.ini.

**Comment by hrydgard** [comment]
Yeah I'm aware that the translation system is a bit of a mess. I invented something simple, and it grew way more unmanagable than I had expected.

**Comment by vnctdj** [comment]
I have almost finished my tool.
Just after I will update all .ini files.
And then I'll open a new issue in order to list all the irregularities :)
We will manage it, @hrydgard !

**Comment by vnctdj** [comment]
My tool works well now :)
I'm currently updating _en_US.ini_... Stay tuned!

**Comment by vnctdj** [comment]
I have just updated all .ini files!
