### ISSUE TITLE
New ini files and a tool to generate PPSSPP translation messages

### ISSUE THREAD

**Issue by gary-ts** [hrydgard/ppsspp-lang#676]
I wrote a tool to generate PPSSPP translation messages.
It can't get some of the messages, but I think it generates better ini files.

Usage:
```
mkdir -p tmp_psp/build
cp get_i18n_messages.rb tmp_psp/
cd tmp_psp/build/
git clone --depth=1 https://github.com/hrydgard/ppsspp.git
git clone --depth=1 https://github.com/hrydgard/ppsspp-lang.git
cp -f ppsspp-lang/* ppsspp/assets/lang/
cd ..
ruby get_i18n_messages.rb
```

Check build/ppsspp/assets/lang/*.ini.new.
I attached new ini files and a tool ([ppsspp_translation.tar.gz](https://github.com/hrydgard/ppsspp-lang/files/2509564/ppsspp_translation.tar.gz)).

Regards.

**Comment by vnctdj** [comment]
That's very interesting as I'm also currently writing a similar tool myself.
I will look at it!

**Comment by gary-ts** [comment]
vnctdj, you always help translators. Thank you for your continuous work.
hrydgard will release ppsspp-1.7.0 soon (https://github.com/hrydgard/ppsspp/commit/6d1d04be523b8a53ee363aad75fb0953e7948a1a),
so maybe our new translation will not be included in that release. :-p

**Comment by gary-ts** [comment]
Thanks hrydgard. PPSSPP is a great emulator.
Some of the translation messages are not "category->T()" style,
so It was difficult to make a translation updater.
vnctdj will make a better tool. :-)

**Comment by gary-ts** [comment]
I updated my translation tool and ini files. 
[ppsspp_translation-20181025.tar.gz](https://github.com/hrydgard/ppsspp-lang/files/2513443/ppsspp_translation-20181025.tar.gz)
This includes all en_US messages. See [en_US.ini.diff.gz](https://github.com/hrydgard/ppsspp-lang/files/2513444/en_US.ini.diff.gz) .

Note:
Comments are removed to sort entries.
Some "&" may be removed.

**Comment by vnctdj** [comment]
If I don't encounter more bugs, my tool should be ready soon.
I can't wait to carefully read your code which looks very promising, @gary-ts !

**Comment by gary-ts** [comment]
> If I don't encounter more bugs, my tool should be ready soon.
Great. I'll use it.

**Comment by hrydgard** [comment]
@gary-ts Next time, please take the time to make a proper pull request, a lot easier for me to manage than unzipping stuff and manually committing.
