### ISSUE TITLE
en_US.ini update

### ISSUE THREAD

**Issue by gary-ts** [hrydgard/ppsspp-lang#690]
Some messages are added/changed.
https://github.com/hrydgard/ppsspp/commit/c19d3fe06a1f3cab3760fac1972f6c4164f9b622
https://github.com/hrydgard/ppsspp/commit/6bc9a96e38d784fcf720ad2944d34ec18e4681fa

Please use this file (if it's ok).
[en_US.ini.gz](https://github.com/hrydgard/ppsspp-lang/files/2548709/en_US.ini.gz)

**Comment by hrydgard** [comment]
Please learn how to make proper pull requests if you plan to continue contributing.

**Comment by gary-ts** [comment]
Ah, you don't accept translation files in Issues.

> if you plan to continue contributing.

en_US.ini should be maintained by programmers.
Please update it after you changed the messages.

**Comment by hrydgard** [comment]
What? No. Anyone can make a pull request, I don't care if you're a programmer or not. Just need to learn a little bit of git.

**Comment by leopard20** [comment]
@hrydgard Since I added this file already, you should probably close this.
