### ISSUE TITLE
[zh_CN.ini] "Buy PPSSPP Gold" text is too wide.

### ISSUE THREAD

**Issue by Narugakuruga** [hrydgard/ppsspp-lang#701]
When translated into Chinese, the text "购买 
PPSSPP 黄金版" will cover the icon on Android (PC hasn't been tested yet ). Can we change it into "购买黄金版" ?

**Comment by Narugakuruga** [comment]
Exist both on Android and PC.

**Comment by hrydgard** [comment]
I had to change it from "Support PPSSPP" to comply with Google Play's policies. It must be at least reasonably clear that it's a link to the play store.

According to Google Translate, your translation seems fine. I don't understand Chinese though, so I'm gonna have to trust it and you :)  So yeah, go for it.

**Comment by Narugakuruga** [comment]
Change made.
