### ISSUE TITLE
What makes those strings translatable?

### ISSUE THREAD

**Issue by vnctdj** [hrydgard/ppsspp-lang#741]
I'm having trouble finding what makes some strings translatable.

1. "error_string" ones, such as :
https://github.com/hrydgard/ppsspp/blob/5a53570b38d7302ea9292ac56a907758b31327a2/Core/Loaders.cpp#L292

2. "failureReason" ones, such as :
https://github.com/hrydgard/ppsspp/blob/5a53570b38d7302ea9292ac56a907758b31327a2/Common/ChunkFile.cpp#L230

Thanks in advance!

**Comment by hrydgard** [comment]
If you trace the function calls outwards (made easier by setting a breakpoint) you can see that eventually the string will be sent through a i18n function. In the first case, the error string eventually ends up in EmuScreen::errorMessage_ which is translated here:

```
		errLoadingFile.append(err->T(errorMessage_.c_str()));
```
in EmuScreen.cpp:1064.

Unfortunately it's quite a mess :)

**Comment by vnctdj** [comment]
Thanks for your help!

Unfortunately I haven't set up a proper debugging environment on my machine, it's obviously more difficult to understand some parts of the code just by reading it :)

**Comment by vnctdj** [comment]
I have finally set up a quick and dirty debug env with Visual Studio Code.
And indeed, it's super easy to find out which i18n function is used for a string...
Sorry for the inconvenience, I should not have been so lazy :)
