### ISSUE TITLE
Issues with translation strings. (Discussion)

### ISSUE THREAD

**Issue by VIRGINKLM** [hrydgard/ppsspp-lang#76]
These strings are untranslatable:
- Load State
- Save State
- Enable Compatibility Server Reports (I bet this one is because it is on the wrong category linked)

Something weird going on with:
- SE Volume
- Nearest, Linear, Linear(CG), Hybrid, Bicubuc, H+B (On graphics, after the selected "Type:" of Texture Filtering/Scaling the selected type strings don't get translated while the buttons do) 

Also I have no clue where (what category) do the Atrac3+ Audio Support screen strings and the Keyboard Mapping strings are located to.

EDIT: Solved.

**Comment by ppmeis** [comment]
DevMenu button,Dev Tools dialog and Registry levels can't be translated:
![image](https://cloud.githubusercontent.com/assets/4381277/5600460/a4c7ad92-92da-11e4-8120-925428e44677.png)
![image](https://cloud.githubusercontent.com/assets/4381277/5600464/b173ecc2-92da-11e4-9ee6-3e74886d23ee.png)

**Comment by sum2012** [comment]
What mean "Block address" and "no Block" ?

**Comment by ppmeis** [comment]
@sum Its related to memory adresses. This dev tool can block an adress to not be processed, its very usefull for catching memory/graphic issues I think.

**Comment by sum2012** [comment]
@ppmeis Thanks explain

**Comment by hrydgard** [comment]
Uh, no. Those strings are from the JIT block viewer.  A jit "block" is a bunch of MIPS (psp) instructions that are translated together into the host system's machine language (x86 or ARM).

**Comment by ppmeis** [comment]
@hrydgard thanks for you better explain. I thought it used for memory adresses because I saw XxXXXXX numbers while using this, so I asociated it to memory 😅 my fault.

**Comment by papel** [comment]
A problem with save states in the pause menu:
![ulus10482_00000](https://cloud.githubusercontent.com/assets/4851122/5689979/69533d24-9859-11e4-9304-bb8935ed910d.jpg)

**Comment by papel** [comment]
I will update the translation, but there are some issues.

Some strings are present in en_US.ini, but I cannot find them in PPSSPP.

[Graphics]
Toggled Speed Limit
Internal Resolution
Window Size
Antialiasing and postprocessing
Partial Vertical Stretch
Immersive Mode

[System]
Cache ISO in RAM
Savestate Slot


And there are some inconsistencies:
In en_US.ini, 'Screen Rotation' is in [Controls], but in PPSSPP it appears in [System].

In en_US.ini, 'Language' is in [Developer] instead of [System].

**Comment by unknownbrackets** [comment]
Cache ISO in RAM only shows up in 64-bit builds.  Immersive Mode only shows up on Android phones on KitKat or later.  Partial Vertical Stretch only shows on mobile devices with a certain range of aspect ratios (e.g. square-ish displays.)

Internal Resolution and Window Size show up when you change the resolution on Windows, as an on-screen message at the top of the screen.

Savestate Slot shows also as an on-screen message when pressing a key that toggles to the next savestate slot.

"Toggled Speed Limit" and "Antialiasing and postprocessing" are no longer present.

Screen Rotation seems to indeed be under Controls, though I'm not sure that makes sense...

"Language" is also shown under Developer, e.g. near the load/save language ini options.

-[Unknown]

**Comment by papel** [comment]
I see.
I have some suggestions to improve the consistency:
* Move 'Internal Resolution', 'Window Size', 'Savestate Slot' to [Screen].
* Move 'Must Restart', 'RestoreDefaultSettings', 'RestoreGameDefaultSettings' to [Dialog].
* Move 'Screen Rotation' and its related strings to [System].

These changes will not be done before version 1.0. Right?

**Comment by unknownbrackets** [comment]
Well, we wouldn't want to break existing translations.  Something will fall through the cracks if we just move things around for organization purposes only.

-[Unknown]

**Comment by vnctdj** [comment]
https://github.com/hrydgard/ppsspp-lang/issues/76#issuecomment-69432426 : this new design for savestates is not finished yet, as stated by @hrydgard, so we should wait until it's definitive :)

**Comment by sum2012** [comment]
As @QWEmct  mention in https://github.com/hrydgard/ppsspp-lang/pull/450#issuecomment-72018938
We cannot transale in the pause screen (within save status)
https://cloud.githubusercontent.com/assets/8009425/5957783/a18cde82-a7ce-11e4-8f26-79b22528e4d7.png

Anyone have idea ?

**Comment by hrydgard** [comment]
@sum2012 , I will fix soon, hang on.

**Comment by QWEmct** [comment]
Thanks, work.
ppsspp-v0.9.9.1-1620-g626e2fc-android.apk
![screenshot_2015-01-29-17-32-47](https://cloud.githubusercontent.com/assets/8009425/5959185/fc6e2618-a7dc-11e4-817a-3448bc113d2d.png)

**Comment by sum2012** [comment]
@hrydgard Thanks a quick fix.
Anyway what is the lang under japanese ?
![1](https://cloud.githubusercontent.com/assets/2177532/5959264/c28b5990-a807-11e4-80ff-c48d68f8179d.jpg)
Why I cannot see the word ?

**Comment by QWEmct** [comment]
@sum2012 
For English, there is no coding support.
![screenshot_2015-01-29-17-53-23](https://cloud.githubusercontent.com/assets/8009425/5959488/cbb92ed4-a7df-11e4-9e66-089a350221fc.png)

**Comment by sum2012** [comment]
@QWEmct Thanks,it is korean lang

**Comment by QWEmct** [comment]
@sum2012 
Thanks, it for me doesn′t work absolutely.
![screenshot_2015-01-29-18-09-08](https://cloud.githubusercontent.com/assets/8009425/5959798/236e99a0-a7e2-11e4-946a-8733c8b2ecfb.png)

**Comment by hrydgard** [comment]
That language works if you use system fonts, unfortunately this only works on Windows for now...

**Comment by QWEmct** [comment]
And I even have no Korean language what to try it.
![screenshot_2015-01-29-18-15-44](https://cloud.githubusercontent.com/assets/8009425/5959929/f03c6656-a7e2-11e4-856f-3facf59fc16a.png)

**Comment by sum2012** [comment]
@hrydgard I am using windows also have that problem.
Rebuild font atlas maybe fix the probrem.
![3](https://cloud.githubusercontent.com/assets/2177532/5960313/74879210-a80f-11e4-8da9-72a3a6ffdabe.jpg)

**Comment by xiushudongfang** [comment]
![010aa6354c96a814cdc31c6b58582d49](https://cloud.githubusercontent.com/assets/8541580/5970323/71834aca-a86c-11e4-9e7d-f7cfd29fc6f0.jpg)
Android：
![qq 20150130104022](https://cloud.githubusercontent.com/assets/8541580/5970322/69f1a144-a86c-11e4-88e8-7c439e562756.png)
Windows:
![qq 20150130104509](https://cloud.githubusercontent.com/assets/8541580/5970360/1361ef86-a86d-11e4-83df-d269f3ad37e4.png)

**Comment by sum2012** [comment]
Hi all,
How to translate "Failed to load state" ?
![1](https://cloud.githubusercontent.com/assets/2177532/5984956/7db52480-a916-11e4-92ca-e8dbe89ff6be.jpg)

**Comment by xiushudongfang** [comment]
Core/SaveState.cpp

**Comment by ppmeis** [comment]
@sum2012 there are strings to these messages:

"Save State Failed ="
"LoadStateDoesntExist ="
"LoadStateWrongVersion ="

Looking for code should it be "Load savestate failed" maybe?

I18NCategory *s = GetI18NCategory("Screen");
			// I couldn't stand the inconsistency.  But trying not to break old lang files.
			const char *i18nLoadFailure = s->T("Load savestate failed", "");
			const char *i18nSaveFailure = s->T("Save State Failed", "");
			if (strlen(i18nLoadFailure) == 0)
				i18nLoadFailure = s->T("Failed to load state");
			if (strlen(i18nSaveFailure) == 0)
				i18nSaveFailure = s->T("Failed to save state");

**Comment by sum2012** [comment]
@ppmeis Thanks that work
Anyway,I share the bad save status (Monster Hunter Portable 3rd HD )
https://drive.google.com/file/d/0B3OaSdeV0L8kdDFudkxzWU9hRFE/view?usp=sharing

**Comment by sum2012** [comment]
There is a small story.
My freind want me that repair "Monster Hunter Portable 3rd HD " game's save,but luckly save status cannot load.

**Comment by sum2012** [comment]
I have update en_US.ini in
https://github.com/hrydgard/ppsspp-lang/commit/3e935ca0ce19b1905b56179245ea914d4712a319

**Comment by papel** [comment]
Excuse me. #458 changed the order of everything. I had ordered everything in the file of my language according to the order that appears in PPSSPP interface. :( Maybe the English file should have been reordered in a better order, before the synchronization of the other files.

**Comment by vnctdj** [comment]
The order of lines can be enhanced, indeed...
Here are the solutions :
- oldest to newest (new strings are added at the end of each category ; the one used at the moment)
- in the order of the UI (need to modify the order if the UI order is edited ; not very practical I think)
- alphabetically (need to know your alphabet ^^)

I personally think the cleanest is alphabetically and it's not very difficult to maintain.
What do you think guys ?

**Comment by ppmeis** [comment]
@vnctdj I think the cleanest way is alphabetically, for some reasons:

Common alphabet will be english because it's used for the beginning of the strings in all inis.
There's no sense to use tab spacing anymore if we use alphabetical order.
Easiest to compare with other languages and to check if there's any line missed.

So LGTM to use alphabetical order IMHO.

**Comment by vnctdj** [comment]
Thank you for your opinion :)
I will put all languages in alphabetical order very soon !

**Comment by vnctdj** [comment]
Done ! All languages updated :)

**Comment by sum2012** [comment]
![1](https://cloud.githubusercontent.com/assets/2177532/12695679/a3a29e86-c790-11e5-960e-fbee6f747d50.jpg)
Anyone know that how to translate "Display Rotation" ? Thanks

**Comment by vnctdj** [comment]
I don't know how to fix this either, I have created [a new issue](https://github.com/hrydgard/ppsspp/issues/8529).

**Comment by hrydgard** [comment]
@sum2012 @vnctdj Fixed it for you :)

**Comment by unknownbrackets** [comment]
Should we close this and open separate issues for separate issues?  We might celebrate this issue's 3-year birthday in a few months.

-[Unknown]

**Comment by vnctdj** [comment]
@hrydgard Thanks !

@unknownbrackets Yes, I guess it would be a good idea, this thread doesn't really make any sense...

**Comment by sum2012** [comment]
Thanks @vnctdj @hrydgard
